### ISSUE TITLE
@dynamic doesn't recognize untyped fields

### ISSUE THREAD

**Issue by ameligrana** [AntonOresten/DynamicStructs.jl#2]
MWE:

```julia
julia> using DynamicStructs

julia> @dynamic struct Spaceship
           name::String
           q
       end

julia> Spaceship("a", 1)
ERROR: MethodError: no method matching Spaceship(::String, ::Int64)

Closest candidates are:
  Spaceship(::String; kwargs...)
   @ Main ~/.julia/dev/DynamicStructs/src/dynamic.jl:83

Stacktrace:
 [1] top-level scope
   @ REPL[3]:1

```

**Comment by AntonOresten** [comment]
Ah, I apologize for the oversight. I just checked for `:(::)` expressions when parsing the fields, not realizing fields are just symbols when untyped.

This has now been fixed in https://github.com/AntonOresten/DynamicStructs.jl/commit/02fcc3db835926009e2f9af040e890d7aab26c03

I've tried to account for some of these annoying edge-cases, but there are always more, like putting fields after an inner constructor.😅Should probably parse all lines of the struct block, identify fields, constructors, and throw an exception if they're in a weird order.

Anyway, thanks for spotting!😄
